#!/bin/bash
# =============================================================================
# setup.sh - Claude Code + Cursor Agent Orchestration 自動セットアップ
#
# Usage:
#   git clone https://github.com/bunta-ishiwata/claude-cursor-orchestration.git
#   cd claude-cursor-orchestration
#   ./setup.sh
#
# もしくは Claude Code に「このリポジトリの setup.sh を実行して」と依頼
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${BLUE}[setup]${NC} $*"; }
ok()   { echo -e "${GREEN}[setup]${NC} $*"; }
warn() { echo -e "${YELLOW}[setup]${NC} $*"; }
err()  { echo -e "${RED}[setup]${NC} $*"; }

# Copy a file into place; prompt before overwriting an existing destination.
install_file() {
  local src="$1" dest="$2"
  if [ ! -f "$src" ]; then
    warn "Missing source: $src"
    return 1
  fi
  if [ -e "$dest" ]; then
    warn "Already exists: $dest"
    read -p "  Overwrite? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      log "Skipping: $dest"
      return 0
    fi
  fi
  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  ok "Installed: $dest"
}

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
HOOKS_DIR="$HOME/.claude-code/hooks"
COMMANDS_DIR="$CLAUDE_DIR/commands"
SETTINGS_FILE="$CLAUDE_DIR/settings.json"

echo ""
echo "=================================================="
echo "  Claude Code + Cursor Agent Orchestration Setup"
echo "=================================================="
echo ""

# ─────────────────────────────────────────────────────
# Step 1: Check prerequisites
# ─────────────────────────────────────────────────────
log "Checking prerequisites..."

# Check Claude Code
if command -v claude &>/dev/null; then
  ok "Claude Code CLI found: $(which claude)"
else
  err "Claude Code CLI not found."
  echo "  Install: https://docs.anthropic.com/en/docs/claude-code"
  exit 1
fi

# Check cursor-agent
CURSOR_BIN="$HOME/.local/bin/cursor-agent"
if [ -x "$CURSOR_BIN" ]; then
  ok "cursor-agent CLI found: $CURSOR_BIN"
  # Check login status
  if "$CURSOR_BIN" status 2>&1 | grep -qi "logged in"; then
    ok "cursor-agent is logged in"
  else
    warn "cursor-agent is not logged in. Run: cursor-agent login"
  fi
else
  err "cursor-agent CLI not found at $CURSOR_BIN"
  echo ""
  echo "  Install with:"
  echo "    curl https://cursor.com/install -fsSL | bash"
  echo "    cursor-agent login"
  echo ""
  read -p "  Continue setup without cursor-agent? (y/N) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
  fi
  warn "Continuing without cursor-agent. Hook will gracefully skip delegation."
fi

# Check Python
if command -v python3 &>/dev/null; then
  ok "Python 3 found: $(python3 --version)"
else
  err "Python 3 not found. Please install Python 3.10+"
  exit 1
fi

echo ""

# ─────────────────────────────────────────────────────
# Step 2: Install Hook script
# ─────────────────────────────────────────────────────
log "Installing Hook script..."

mkdir -p "$HOOKS_DIR"
HOOK_FILE="$HOOKS_DIR/cursor-delegate.sh"

# Generate hook with correct path to cursor_dispatch.py
cat > "$HOOK_FILE" <<HOOKEOF
#!/bin/bash
# Auto-generated by claude-cursor-orchestration setup.sh
# Delegates coding tasks from Claude Code to Cursor Agent

if [ ! -f "\$HOME/.local/bin/cursor-agent" ]; then
  exit 0
fi

cat <<'EOF'
{
  "hookSpecificOutput": {
    "hookEventName": "UserPromptSubmit",
    "additionalContext": "CURSOR AGENT DELEGATION ACTIVE: When this task involves writing, editing, or generating code (including creating files, refactoring, fixing bugs, adding features), you MUST use the /app-development skill to orchestrate the full development flow. This skill dispatches coding work to Cursor Agent via CursorACP (python3 ${REPO_DIR}/src/cursor_dispatch.py) and follows a structured Phase 0-8 pipeline: conception → design review → parallel implementation → integration → quality review (6 parallel) → fixes → E2E → deploy → PR. For read-only analysis, planning, reviews, and non-code tasks, handle them yourself directly without the skill."
  }
}
EOF
HOOKEOF

chmod +x "$HOOK_FILE"
ok "Hook installed: $HOOK_FILE"

# ─────────────────────────────────────────────────────
# Step 3: Update Claude Code settings.json
# ─────────────────────────────────────────────────────
log "Configuring Claude Code settings..."

mkdir -p "$CLAUDE_DIR"

if [ -f "$SETTINGS_FILE" ]; then
  # Check if hook is already configured
  if grep -q "cursor-delegate.sh" "$SETTINGS_FILE" 2>/dev/null; then
    ok "Hook already registered in settings.json"
  else
    # Backup existing settings
    cp "$SETTINGS_FILE" "${SETTINGS_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    warn "Backed up existing settings.json"

    # Add hook using Python (handles JSON merging properly)
    python3 - "$SETTINGS_FILE" "$HOOK_FILE" <<'PYEOF'
import json, sys

settings_path = sys.argv[1]
hook_cmd = sys.argv[2]

with open(settings_path) as f:
    settings = json.load(f)

# Ensure hooks.UserPromptSubmit exists
hooks = settings.setdefault("hooks", {})
uph = hooks.setdefault("UserPromptSubmit", [])

# Add our hook entry
new_hook = {
    "hooks": [{
        "type": "command",
        "command": hook_cmd
    }]
}

# Check if already present
already = any(
    any(h.get("command", "").endswith("cursor-delegate.sh") for h in entry.get("hooks", []))
    for entry in uph
)

if not already:
    uph.append(new_hook)
    with open(settings_path, "w") as f:
        json.dump(settings, f, indent=2, ensure_ascii=False)
    print("Hook added to settings.json")
else:
    print("Hook already present in settings.json")
PYEOF
    ok "settings.json updated"
  fi
else
  # Create new settings.json
  cat > "$SETTINGS_FILE" <<SJEOF
{
  "hooks": {
    "UserPromptSubmit": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "$HOOK_FILE"
          }
        ]
      }
    ]
  }
}
SJEOF
  ok "Created new settings.json with hook"
fi

# ─────────────────────────────────────────────────────
# Step 4: Install app-development Skill
# ─────────────────────────────────────────────────────
log "Installing app-development skill..."

mkdir -p "$COMMANDS_DIR"
SKILL_FILE="$COMMANDS_DIR/app-development.md"

if [ -f "$SKILL_FILE" ]; then
  warn "Skill file already exists: $SKILL_FILE"
  read -p "  Overwrite? (y/N) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    log "Skipping skill installation"
  else
    cp "$REPO_DIR/skills/app-development-example.md" "$SKILL_FILE" 2>/dev/null || \
    generate_skill "$SKILL_FILE"
    ok "Skill updated: $SKILL_FILE"
  fi
else
  # Generate skill file
  cat > "$SKILL_FILE" <<SKILLEOF
---
description: "App Development Orchestrator - delegates coding to Cursor Agent"
---

# App Development Orchestrator

You are an orchestrator. Claude Code handles planning/review/deploy, Cursor Agent handles implementation.

## Dispatch Command

\`\`\`bash
DISPATCH="python3 ${REPO_DIR}/src/cursor_dispatch.py"
\`\`\`

## Roles

- **Claude Code** (you): requirements, design, code review, git operations, deployment
- **Cursor Agent** (via dispatch): code generation, file editing, test writing, refactoring

## Pipeline

1. **Phase 0 - Conception**: Clarify requirements with user
2. **Phase 1 - Design**: Create design, dispatch review to Cursor (\`--mode plan\`)
3. **Phase 2 - Implementation**: Split into independent tasks, dispatch in parallel
   \`\`\`bash
   \$DISPATCH parallel --workspace \$PWD --tasks '["task1", "task2"]' --model composer-2-fast
   \`\`\`
4. **Phase 3 - Integration**: Review all generated code for conflicts
5. **Phase 4 - Quality Review**: Dispatch 6 parallel review tasks
6. **Phase 5 - Fixes**: Dispatch fix tasks based on review findings
7. **Phase 6 - E2E Testing**: Dispatch test execution
8. **Phase 7 - Deploy**: Handle deployment directly (gcloud, etc.)
9. **Phase 8 - PR**: Create branch, commit, push, create PR

## Single Task Dispatch

\`\`\`bash
\$DISPATCH "<prompt>" --workspace \$PWD --model composer-2-fast
\`\`\`

## Important

- Always use \`--workspace\` to specify the project directory
- Use \`composer-2-fast\` for implementation speed
- Use analysis models for code review depth
- Check \`result.success\` and \`result.has_question\` in the JSON output
- If Cursor asks a question, answer it and resume with \`--resume <session_id>\`
SKILLEOF
  ok "Skill installed: $SKILL_FILE"
fi

# ─────────────────────────────────────────────────────
# Step 5: Make scripts executable
# ─────────────────────────────────────────────────────
log "Setting file permissions..."
chmod +x "$REPO_DIR/src/"*.sh "$REPO_DIR/src/"*.py 2>/dev/null || true
chmod +x "$REPO_DIR/hooks/"*.sh 2>/dev/null || true
ok "Permissions set"

# ─────────────────────────────────────────────────────
# Step 6: Cursor skills, subagents (agents), and rules
# ─────────────────────────────────────────────────────
log "Installing Cursor-side configuration (skills, agents, rules)..."

CURSOR_CFG="$HOME/.cursor"
CURSOR_SKILLS="$CURSOR_CFG/skills"
CURSOR_AGENTS="$CURSOR_CFG/agents"
CURSOR_RULES="$CURSOR_CFG/rules"
BUNDLE_DIR="$REPO_DIR/cursor-config"

if [ ! -d "$BUNDLE_DIR/skills" ]; then
  warn "cursor-config/skills not found — skip Cursor bundle (clone complete repo?)"
else
  mkdir -p "$CURSOR_SKILLS" "$CURSOR_AGENTS" "$CURSOR_RULES"
  for skill_path in "$BUNDLE_DIR/skills"/*; do
    [ -d "$skill_path" ] || continue
    sname="$(basename "$skill_path")"
    install_file "$skill_path/SKILL.md" "$CURSOR_SKILLS/$sname/SKILL.md" || true
  done
  for agent_file in "$BUNDLE_DIR/agents"/*.md; do
    [ -f "$agent_file" ] || continue
    install_file "$agent_file" "$CURSOR_AGENTS/$(basename "$agent_file")" || true
  done
  install_file "$BUNDLE_DIR/rules/CURSOR_GLOBAL_RULES.md" "$CURSOR_CFG/CURSOR_GLOBAL_RULES.md" || true
  install_file "$BUNDLE_DIR/rules/global-agent-workflow.mdc" "$CURSOR_RULES/global-agent-workflow.mdc" || true
  ok "Cursor configuration step finished (see $BUNDLE_DIR/README.md)"
fi

# ─────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────
echo ""
echo "=================================================="
echo -e "  ${GREEN}Setup complete!${NC}"
echo "=================================================="
echo ""
echo "  Installed:"
echo "    Hook:    $HOOK_FILE"
echo "    Skill:   $SKILL_FILE"
echo "    Bridge:  $REPO_DIR/src/cursor_dispatch.py"
echo "    Cursor:  $CURSOR_CFG (skills / agents / rules from cursor-config/ when present)"
echo ""
echo "  What happens now:"
echo "    1. Open Claude Code in any project"
echo "    2. Ask it to write code (e.g. 「認証機能を追加して」)"
echo "    3. Claude Code automatically delegates to Cursor Agent"
echo ""

if [ ! -x "$CURSOR_BIN" ]; then
  echo -e "  ${YELLOW}Note: Install cursor-agent to enable delegation:${NC}"
  echo "    curl https://cursor.com/install -fsSL | bash"
  echo "    cursor-agent login"
  echo ""
fi

echo "  To test manually:"
echo "    python3 $REPO_DIR/src/cursor_dispatch.py --status"
echo ""
